export const skills = [
    { name: 'HTML', img: 'https://cdn.worldvectorlogo.com/logos/html-1.svg'},
    { name: 'CSS', img: 'https://cdn.worldvectorlogo.com/logos/css-3.svg'},
    { name: 'JavaScript', img: 'https://cdn.worldvectorlogo.com/logos/logo-javascript.svg'},
    { name: 'TypeScript', img: 'https://cdn.worldvectorlogo.com/logos/typescript.svg'},
    { name: 'React', img: 'https://cdn.worldvectorlogo.com/logos/react-2.svg'},
    { name: 'Next JS', img: 'https://seeklogo.com/images/N/next-js-icon-logo-EE302D5DBD-seeklogo.com.png'},
    { name: 'Redux', img: 'https://cdn.worldvectorlogo.com/logos/redux.svg'},
    { name: 'React Query', img: 'https://seeklogo.com/images/R/react-query-logo-1340EA4CE9-seeklogo.com.png'},
    { name: 'Tailwind CSS', img: 'https://cdn.worldvectorlogo.com/logos/tailwind-css-2.svg'},
    { name: 'Material UI', img: 'https://cdn.worldvectorlogo.com/logos/material-ui-1.svg'},
    { name: 'Chakra UI', img: 'https://bestofjs.org/logos/chakra-ui.dark.svg'},
    { name: 'Node.js', img: 'https://cdn.worldvectorlogo.com/logos/nodejs-icon.svg'},
    { name: 'Express', img: 'https://img.icons8.com/ios/512/express-js.png'},
    { name: 'Postman', img: 'https://cdn.worldvectorlogo.com/logos/postman.svg'},
]